/**
 * CLI Script to Delete a Student Project
 * Usage: npm run delete
 * 
 * This script allows you to safely delete a student project from the database.
 * It handles:
 * - Deleting the project from projects_students
 * - Automatically removing associated student_to_projects relations (cascade delete)
 * - Appending deletion SQL to 006_delete_student_project.sql for manual batch execution
 */

import db from './index';
import { Projects, StudentToProjects } from './schema';
import { eq } from 'drizzle-orm';
import { sql } from 'drizzle-orm';
import { createInterface } from 'readline';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';

const readline = createInterface({
    input: process.stdin,
    output: process.stdout
});

function question(prompt: string): Promise<string> {
    return new Promise((resolve) => {
        readline.question(prompt, resolve);
    });
}

async function executeDeleteSQL(filepath: string) {
    console.log('\n🚀 Executing deletion SQL...');
    
    try {
        const sqlContent = readFileSync(filepath, 'utf-8');
        
        // Extract DELETE statements (ignoring comments and empty lines)
        const lines = sqlContent.split('\n');
        const deleteStatements: string[] = [];
        
        for (const line of lines) {
            const trimmed = line.trim();
            if (trimmed.startsWith('DELETE FROM')) {
                deleteStatements.push(trimmed);
            }
        }
        
        if (deleteStatements.length === 0) {
            console.log('ℹ️  No DELETE statements found in the file');
            return;
        }
        
        // Execute each DELETE statement
        for (const statement of deleteStatements) {
            try {
                await db.execute(sql.raw(statement));
                console.log(`✅ Executed: ${statement.substring(0, 60)}...`);
            } catch (err) {
                console.error(`❌ Error executing statement:`, err);
                throw err;
            }
        }
        
        console.log('\n✅ All deletions executed successfully!');
        
        // Clear the file after successful execution
        const header = `-- Delete Student Projects SQL File\n-- This file contains SQL statements to delete student projects\n-- Execute manually when ready\n-- Auto-generated by npm run delete\n\n`;
        writeFileSync(filepath, header, 'utf-8');
        console.log('🧹 Cleared the delete SQL file');
        
    } catch (error) {
        console.error('❌ Error executing SQL:', error);
        throw error;
    }
}

async function deleteProject() {
    console.log('\n🗑️  Delete Student Project Script\n');
    console.log('⚠️  WARNING: This will delete a project and all its student relations!\n');

    try {
        // Fetch all projects
        const allProjects = await db.select().from(Projects);
        
        if (allProjects.length === 0) {
            console.log('❌ No projects found in the database.');
            readline.close();
            process.exit(0);
        }

        console.log('📋 Available Projects:\n');
        allProjects.forEach((project, index) => {
            console.log(`${index + 1}. [ID: ${project.id}] ${project.title}`);
            console.log(`   URL: ${project.URLName}`);
            console.log(`   GitHub: ${project.githubRepoURL}\n`);
        });

        // Get project selection
        const selection = await question('Enter the number of the project to delete (or "cancel" to exit): ');
        
        if (selection.toLowerCase() === 'cancel') {
            console.log('❌ Cancelled.');
            readline.close();
            process.exit(0);
        }

        const selectedIndex = parseInt(selection) - 1;
        
        if (isNaN(selectedIndex) || selectedIndex < 0 || selectedIndex >= allProjects.length) {
            console.log('❌ Invalid selection.');
            readline.close();
            process.exit(1);
        }

        const projectToDelete = allProjects[selectedIndex];

        // Get student relations
        const studentRelations = await db
            .select()
            .from(StudentToProjects)
            .where(eq(StudentToProjects.projectStudentId, projectToDelete.id));

        console.log(`\n⚠️  You are about to delete:\n`);
        console.log(`   Project: ${projectToDelete.title}`);
        console.log(`   ID: ${projectToDelete.id}`);
        console.log(`   URL Name: ${projectToDelete.URLName}`);
        console.log(`   Student Relations: ${studentRelations.length}`);

        // Final confirmation
        const confirm = await question('\n⚠️  Type "DELETE" to confirm: ');
        
        if (confirm.toUpperCase() !== 'DELETE') {
            console.log('❌ Deletion cancelled.');
            readline.close();
            process.exit(0);
        }

        // Generate SQL statements
        const sqlStatements = [
            ``,
            `-- Delete Student Project: ${projectToDelete.title}`,
            `-- Generated at: ${new Date().toISOString()}`,
            `-- Project ID: ${projectToDelete.id}`,
            ``,
            `-- Delete student-to-project relations (will cascade automatically, but explicit for clarity)`,
            `DELETE FROM student_to_projects WHERE project_student_id = ${projectToDelete.id};`,
            ``,
            `-- Delete the project`,
            `DELETE FROM projects_students WHERE id = ${projectToDelete.id};`,
            ``,
        ];

        const sqlContent = sqlStatements.join('\n');
        const filepath = join(__dirname, 'migrations', '006_delete_student_project.sql');

        // Read existing content if file exists
        let existingContent = '';
        if (existsSync(filepath)) {
            existingContent = readFileSync(filepath, 'utf-8');
        } else {
            // Create file with header if it doesn't exist
            existingContent = `-- Delete Student Projects SQL File\n-- This file contains SQL statements to delete student projects\n-- Execute manually when ready\n`;
        }

        // Append new deletion statements
        const updatedContent = existingContent + sqlContent;
        writeFileSync(filepath, updatedContent, 'utf-8');
        
        console.log(`\n✅ Deletion SQL appended to: ${filepath}`);
        
        // Ask if user wants to execute now
        const executeNow = await question('\n📋 Do you want to execute the SQL file now? (yes/no): ');
        
        if (executeNow.toLowerCase() === 'yes' || executeNow.toLowerCase() === 'y') {
            await executeDeleteSQL(filepath);
        } else {
            console.log('\n📋 To execute all deletions later, run:');
            console.log(`   psql <your-database-connection-string> -f ${filepath}`);
            console.log('\nOr copy and paste the SQL statements into your database client.');
            console.log('\n⚠️  Remember to clear the file after execution!');
        }


    } catch (error) {
        console.error('\n❌ Error:', error);
        process.exit(1);
    } finally {
        readline.close();
    }
}

// Run the script
deleteProject()
    .then(() => {
        console.log('\n✨ Script completed.');
        process.exit(0);
    })
    .catch((error) => {
        console.error('\n❌ Fatal error:', error);
        process.exit(1);
    });
